baseURL = 'https://stringtune.com/'
languageCode = 'en-us'
title = 'StringTune Online Tuner - Best Online Instrument Tuner with mic'

DefaultContentLanguage = "en"
disableKinds = ["taxonomy", "taxonomyTerm"]
theme = "stringtune-dark"

[languages]
  [languages.en]
    title = "StringTune Online Tuner - Best Online Instrument Tuner with mic"
    description = "Tune your guitar, bass, ukulele, or any other string instrument with our free, easy-to-use online tuner which shows the note frequency. Optimized for mobile devices!"
    languageName = "English"
  [languages.es]
    title = "Spanish title here"
    description = "Spanish description here"
    languageName = "Español"

